// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my Eclosia profile",
  description: "Return the signed-in user's Eclosia profile: first name, email, plan, premium status, current streak.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("first_name, email, plan_type, is_premium, current_streak, has_initiation_access, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-journal-entries.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_journal_entries_default = defineTool2({
  name: "list_journal_entries",
  title: "List my journal entries",
  description: "Return the signed-in user's most recent private journal entries, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("How many entries to return (1-50, default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("private_journal_entries").select("id, created_at, content, mood, tags").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-journal-entry.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_journal_entry_default = defineTool3({
  name: "create_journal_entry",
  title: "Create a journal entry",
  description: "Add a new private journal entry for the signed-in user. Use for reflections, feelings, or notes the user dictates.",
  inputSchema: {
    content: z2.string().trim().min(1).describe("The journal entry text."),
    mood: z2.string().trim().max(40).optional().describe("Optional short mood label (e.g. 'calme', 'tendue').")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ content, mood }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("private_journal_entries").insert({ user_id: ctx.getUserId(), content, mood: mood ?? null }).select("id, created_at, content, mood").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Entry saved (id ${data?.id}).` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/list-emotion-checkins.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_emotion_checkins_default = defineTool4({
  name: "list_emotion_checkins",
  title: "List my emotion check-ins",
  description: "Return the signed-in user's most recent emotion check-ins (mood, intensity, notes), newest first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("How many check-ins to return (1-100, default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("emotion_checkins").select("id, created_at, emotion, intensity, note").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 30);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { checkins: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-transformation-portraits.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_transformation_portraits_default = defineTool5({
  name: "list_transformation_portraits",
  title: "List my transformation portraits",
  description: "Return the signed-in user's monthly transformation portraits (AI-generated reflection of their journey), newest first.",
  inputSchema: {
    limit: z4.number().int().min(1).max(24).optional().describe("How many portraits to return (1-24, default 6).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser5(ctx);
    const { data, error } = await supabase.from("transformation_portraits").select("id, created_at, period_start, period_end, summary, insights").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 6);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { portraits: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-ambassador-impact.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser6(ctx) {
  return createClient6(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_ambassador_impact_default = defineTool6({
  name: "get_my_ambassador_impact",
  title: "Get my ambassador impact",
  description: "Return the signed-in user's Eclosia ambassador stats: tier, referral code, commissions earned and pending, moms accompanied, next tier progress. Only meaningful if the user is enrolled as an ambassador.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser6(ctx);
    const { data, error } = await supabase.rpc("get_my_ambassador_impact");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { impact: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mpadkxqomykztvqrnmfv";
var mcp_default = defineMcp({
  name: "eclosia-mcp",
  title: "Eclosia",
  version: "0.1.0",
  instructions: "Tools for Eclosia (Digital Maman Libre), a wellbeing companion for women rebuilding after a storm. Each caller is a signed-in Eclosia user; all tools read and write only that user's own data (journal, emotion check-ins, monthly transformation portraits, ambassador impact). Use `create_journal_entry` when the user dictates a reflection, `list_journal_entries` / `list_emotion_checkins` / `list_transformation_portraits` to look back at their journey, and `get_my_profile` / `get_my_ambassador_impact` for account and referral information.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    list_journal_entries_default,
    create_journal_entry_default,
    list_emotion_checkins_default,
    list_transformation_portraits_default,
    get_my_ambassador_impact_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
